name: Build aarch64

on:
  push:
    branches:
      - ci/arm64-android
  workflow_dispatch:

env:
  PYTHONUTF8: 1
  VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
jobs:

  build-ubuntu:
    runs-on: ubuntu-20.04
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: install
        run: sudo apt-get install fuse libfuse-dev clang-12
      - name: Get latest Github release of vcpkg
        env:
          GITHUB_TOKEN: ${{ github.token }}
        uses: cardinalby/git-get-release-action@v1
        id: get-latest-vcpkg-release
        with:
          latest: true
          repo: microsoft/vcpkg
          prerelease: false
          draft: false
      - name: checkout-vcpkg
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/vcpkg
          repository: microsoft/vcpkg
          ref: '${{ steps.get-latest-vcpkg-release.outputs.tag_name }}'
          fetch-depth: 1
      - name: build-test
        env:
          CC: clang-12
          CXX: clang++-12
          VCPKG_KEEP_ENV_VARS: "CC;CXX"
        run: python3 build.py --triple=arm64-linux --lto --enable_unit_test --enable_integration_test --vcpkg_root=${{ github.workspace }}/vcpkg --build_root=./build
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          path: build/securefs
          name: securefs-arm64-android-test
